<?php

/**
 * @file
 * Contains \Drupal\geocoder\Plugin\Geocoder\InputFormatInterface.
 */

namespace Drupal\geocoder\Plugin\Geocoder;

use Drupal\Core\Form\FormStateInterface;
use Drupal\geocoder\Plugin\GeocoderPluginInterface;

interface InputFormatInterface extends GeocoderPluginInterface {
  /**
   * Massages the form values into the format expected for field values.
   *
   * @param array $values
   *   The submitted form values produced by the widget.
   *   - If the widget does not manage multiple values itself, the array holds
   *     the values generated by the multiple copies of the $element generated
   *     by the formElement() method, keyed by delta.
   *   - If the widget manages multiple values, the array holds the values
   *     of the form element generated by the formElement() method.
   * @param array $form
   *   The form structure where field elements are attached to. This might be a
   *   full form structure, or a sub-element of a larger form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The form state.
   *
   * @return array
   *   An array of field values, keyed by delta.
   */
  public function massageFormValues(array $values, array $form, FormStateInterface $form_state);
}